### PR TITLE
elsevier_package.py: fix bug in calculation of number of pages

### PR DESCRIPTION
**Pull request by fschwenn**
* Replaces lastpage - firstpage by lastpage - firstpage + 1

Signed-off-by: fschwenn <florian.schwennsen@desy.de>

### CODE REVIEW

**Comment by jalavik** [comment]
Thanks @fschwenn 

Can you update the `tests/elsevier_package_tests.py` to:
   * Add a test for this calculation to avoid a similar mistake (in case of refactoring)
   * Amend the sample output record to comply with this change `tests/data/sample_consyn_output.xml` (e.g. setting the correct page number)

**Comment by fschwenn** [comment]
Hi Jan, 

isnt it enough to correct tests/data/sample_consyn_output.xml ? 
test_get_record(self) will check it, right? 

Cheers, 
Florian 

-- 
Florian Schwennsen 
Deutsches Elektronen-Synchrotron DESY 
Building 01 Room O1.446 
phone: +49-40-8998-6190

**Comment by jalavik** [comment]
Hi @fschwenn. Indeed that is enough.

PS: You can update your pull request with git push -f (for `--force`) to the same branch (e.g. `elsepagenum`) instead of closing and opening a new one.

**Comment by fschwenn** [comment]
* Replaces lastpage - firstpage by lastpage - firstpage + 1

* Correct tests/data/sample_consyn_output.xml
  accordingly.

Signed-off-by: fschwenn <florian.schwennsen@desy.de>

**Comment by jalavik** [comment]
@fschwenn Thanks!

**Pull request merged**
